In [6]:
import pandas as pd
f = pd.read_csv("./tweets.csv")

In [7]:
f

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1260216113872334849,1260216113872334849,1589293909000,2020-05-12,14:31:49,UTC,1027086041998450688,btc_macro,Bitcoin Macro,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1027086041998450688', 'username'...",NaN,NaN,NaN,NaN
1,1260214518296137728,1260214518296137728,1589293529000,2020-05-12,14:25:29,UTC,916257050,angelobtc,Angeloà¸¿TC,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '916257050', 'username': 'AngeloB...",NaN,NaN,NaN,NaN
2,1260083060642627585,1260083060642627585,1589262187000,2020-05-12,05:43:07,UTC,999947328621395968,bybit_official,Bybit,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '999947328621395968', 'username':...",NaN,NaN,NaN,NaN
3,1259997397691719682,1259997397691719682,1589241763000,2020-05-12,00:02:43,UTC,13418472,woonomic,Willy Woo,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '13418472', 'username': 'woonomic'}]",NaN,NaN,NaN,NaN
4,1259966188869652480,1259966188869652480,1589234323000,2020-05-11,21:58:43,UTC,1027086041998450688,btc_macro,Bitcoin Macro,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1027086041998450688', 'username'...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,914054939453751309,914054939453751309,1506762654000,2017-09-30,09:10:54,UTC,877807935493033984,binance,Binance,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '877807935493033984', 'username':...",NaN,NaN,NaN,NaN
1255,908290390742130688,908290390742130688,1505388279000,2017-09-14,11:24:39,UTC,877807935493033984,binance,Binance,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '877807935493033984', 'username':...",NaN,NaN,NaN,NaN
1256,907611550831099904,907611550831099904,1505226430000,2017-09-12,14:27:10,UTC,877807935493033984,binance,Binance,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '877807935493033984', 'username':...",NaN,NaN,NaN,NaN
1257,906501829046919168,906501829046919168,1504961852000,2017-09-09,12:57:32,UTC,877807935493033984,binance,Binance,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '877807935493033984', 'username':...",NaN,NaN,NaN,NaN
1258,898653841658232832,898653841658232832,1503090746000,2017-08-18,21:12:26,UTC,2917040642,ubiqsmart,Ubiq,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '2917040642', 'username': 'ubiqsm...",NaN,NaN,NaN,NaN

In [19]:
import nltk
from nltk.corpus import stopwords
from nltk import bigrams
import re
from textblob import TextBlob
import networkx
import networkx as nx

In [20]:
def remove_url_punctuation(txt):
    """Replace URLs found in a text string with nothing 
    (i.e. it will remove the URL from the string).

    Parameters
    ----------
    txt : string
        A text string that you want to parse and remove urls.

    Returns
    -------
    The same txt string with url's removed.
    """
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    no_url = url_pattern.sub(r'', txt)
    
    punct_pattern = re.compile(r'[^\w\s]')
    no_punct = punct_pattern.sub(r'', no_url)
    
    # Clean up punctuation (including pound signs)
    return no_punct

In [21]:
tweet_no_urls = [remove_url_punctuation(f["tweet"])]

TypeError: expected string or bytes-like object