In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("PriceTweet.csv")

Normalizing values

In [6]:
time_len = data.shape[0]
print(time_len)
x = data.filter(['vader_sent_hourly mean','Close','Daily Weight count',"movement"])

from sklearn import preprocessing

xx = x.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(xx)
#df = pd.DataFrame(x_scaled)
print(x_scaled)

33127
[[0.00046798]
 [0.00090379]
 [0.00090379]
 ...
 [0.36165301]
 [0.36165301]
 [0.36165301]]

In [5]:
data1 = pd.read_csv("noads_tweets.csv")
data2 = pd.read_csv("/Users/jinny/Desktop/3/Capstone/Price prediction/price.csv")

In [6]:
data1 = pd.read_csv("noads_tweets.csv")

In [7]:
data = pd.merge(data1, data2, on='date', how='inner')

In [49]:
data

,Unnamed: 0,id,DATETIME,date,tweet,username,nlikes,nreplies,nretweets,cleaned_data,blob_sent,ad_count,adwords,Open,High,Low,Close,Volume,MarketCap
0,22613,6.010000e+17,2015-05-19 22:59,2015-05-19,The only thing that can stop a bad guy with a ...,mattblaze,188.0,8.0,214.0,The only thing that can stop a bad guy with a ...,3.700000e-17,0,[],233.04,234.15,231.82,231.95,14241900,3.288950e+09
1,12192,6.020000e+17,2015-05-22 11:04,2015-05-22,"In 2010, two pizzas for 10,000 BTC were bought...",nejc_kodric,385.0,25.0,483.0,In two pizzas for BTC were bought...,0.000000e+00,0,[],235.32,240.97,235.06,240.35,27003000,3.410712e+09
2,12205,6.020000e+17,2015-05-22 11:04,2015-05-22,"In 2010, two pizzas for 10,000 BTC were bought...",nejc_kodric,385.0,25.0,483.0,In two pizzas for BTC were bought...,0.000000e+00,0,[],235.32,240.97,235.06,240.35,27003000,3.410712e+09
3,22612,6.020000e+17,2015-05-23 17:40,2015-05-23,"Regarding crypto wars 2.0, why stop at crypto?...",dotMudge,157.0,20.0,275.0,Regarding crypto wars why stop at crypto ...,-7.000000e-01,0,[],240.29,241.02,238.69,238.87,14605000,3.390436e+09
4,22611,6.030000e+17,2015-05-26 0:36,2015-05-26,I've built my own crypto pic.twitter.com/8AZl...,old_sound,1708.0,18.0,2565.0,I ve built my own crypto,0.000000e+00,0,[],237.10,238.24,235.69,237.12,16425000,3.368067e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33122,13492,1.210000e+18,2019-12-31 16:28,2019-12-31,"Today, we stand before the dawn of a new decad...",tylerwinklevoss,4077.0,239.0,878.0,Today we stand before the dawn of a new decad...,6.818182e-02,0,[],7294.44,7335.29,7169.78,7193.60,21167946112,1.300000e+11
33123,3184,1.210000e+18,2019-12-31 20:13,2019-12-31,A quick @chrisolave_ appreciation tweet before...,zswartz,3701.0,37.0,308.0,A quick chrisolave appreciation tweet before...,2.174242e-01,0,[],7294.44,7335.29,7169.78,7193.60,21167946112,1.300000e+11
33124,3284,1.210000e+18,2019-12-31 20:13,2019-12-31,A quick @chrisolave_ appreciation tweet before...,zswartz,3701.0,37.0,308.0,A quick chrisolave appreciation tweet before...,2.174242e-01,0,[],7294.44,7335.29,7169.78,7193.60,21167946112,1.300000e+11
33125,3182,1.210000e+18,2019-12-31 23:29,2019-12-31,Take a selfie ????! Who is BEST DRESSED for Ne...,Rhett800cc,365.0,238.0,286.0,Take a selfie Who is BEST DRESSED for Ne...,6.454545e-01,0,[],7294.44,7335.29,7169.78,7193.60,21167946112,1.300000e+11
33126,3262,1.210000e+18,2019-12-31 23:29,2019-12-31,Take a selfie ????! Who is BEST DRESSED for Ne...,Rhett800cc,364.0,238.0,286.0,Take a selfie Who is BEST DRESSED for Ne...,6.454545e-01,0,[],7294.44,7335.29,7169.78,7193.60,21167946112,1.300000e+11

In [111]:
data2["date"]= pd.to_datetime(data2["date"])

In [112]:
data1["date"]= pd.to_datetime(data1["date"])

In [50]:
data.to_csv('PriceTweet.csv')